name: Build and publish the Containers

on:
  push:
    branches:
      - build_workflow

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOTPATH: /home/runner/work/CYBERTEC-pg-container/CYBERTEC-pg-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'          

      - name: Build base
        run: |
          make base