name: Build and publish the Containers

on:
  push:
    branches:
      - build_workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Move files to desired path
        run: |
          mkdir -p /src/github.com/cybertec/cybertec-pg-container
          mv * /src/github.com/cybertec/cybertec-pg-container
          

      - name: Build base
        run: |
          make base