name: Build and publish the Containers

on:
  push:
    branches:
      - build_workflow

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOTPATH: /home/runner/work/CYBERTEC-pg-container/CYBERTEC-pg-container
      BASEOS: rocky9
      BUILD: 1





    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'          

      - name: Build base$
        id: build-base
        run: |
          make base


  tag:
    
    runs-on: ubuntu-latest

    env:
      IMAGEPRAEFIX: docker.io/cybertecpostgresql/cybertec-pg-container-dev
      BASEOS: rocky9
      BUILD: 1
      PGVERSION: 16.3
      TYPE: dev

    needs: build
    
    steps:
      - name: Tag and push container1
        run: |
          docker tag cybertec-pg-container/base:$BASEOS-$BUILD $IMAGEPRAEFIX/base:$BASEOS-$BUILD-$TYPE


